name: Deploy

on: [push]

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/master' }} 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Dashboard code
      uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: latest
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: pnpm
    - name: Install package and build
      run: |
        pnpm install --frozen-lockfile
        pnpm build
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: dist
        fqdn: clash.razord.top
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sdcom/mihomo-and-dashboard:latest
